apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-spec-mutator
  namespace: injector
  labels:
    app: pod-spec-mutator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-spec-mutator
  template:
    metadata:
      labels:
        app: pod-spec-mutator
    spec:
      containers:
        - name: pod-spec-mutator
          image: docker.io/mheers/pod-spec-mutator:ea6c533
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: cert
              mountPath: "/tmp/k8s-webhook-server/serving-certs"
              readOnly: true
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PATCHES
              value: '{"patches": [{"podNameRegex": "demo","pod": {"spec": {"containers": [{"name": "postgres","imagePullPolicy": "Never","image": ""}],"hostAliases": [{"ip": "192.168.1.100","hostnames": ["foo.local"]}]}}}]}'
      volumes:
        - name: cert
          secret:
            secretName: pod-spec-mutator-tls
