apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: pod-spec-mutator
  annotations:
    cert-manager.io/inject-ca-from: injector/pod-spec-mutator-cert
webhooks:
  - name: pod-spec-mutator.example.com
    clientConfig:
      service:
        name: pod-spec-mutator
        namespace: injector
        path: "/mutate"
        port: 443
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: "Namespaced"
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: injector
    matchConditions:
      - expression: '!object.metadata.generateName.startsWith("pod-spec-mutator-")'
        name: exclude-ourselves
    admissionReviewVersions: ["v1"]
    sideEffects: None
